function test(locals) {
var jade_debug = [ new jade.DebugItem( 1, "index.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;

jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 2, "index.jade" ));
buf.push("<html lang=\"en\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "index.jade" ));
buf.push("<head>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "index.jade" ));
buf.push("<meta charset=\"utf-8\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "index.jade" ));
buf.push("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "index.jade" ));
buf.push("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 8, "index.jade" ));
buf.push("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags-->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 8, "index.jade" ));
buf.push("<meta name=\"description\" content=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "index.jade" ));
buf.push("<meta name=\"author\" content=\"\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "index.jade" ));
buf.push("<link rel=\"icon\" href=\"icon.ico\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 11, "index.jade" ));
buf.push("<script src=\"js/angular.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 12, "index.jade" ));
buf.push("<script src=\"js/jquery-2.1.3.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 13, "index.jade" ));
buf.push("<script src=\"/js/socket.io.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "index.jade" ));
buf.push("<script src=\"js/key_controls.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 15, "index.jade" ));
buf.push("<script src=\"js/score_interactions.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 16, "index.jade" ));
buf.push("<script src=\"js/adjustClocks.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 17, "index.jade" ));
buf.push("<title>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 17, jade_debug[0].filename ));
buf.push("Scoreboard Application");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 19, "index.jade" ));
buf.push("<!-- Bootstrap core CSS-->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 19, "index.jade" ));
buf.push("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 21, "index.jade" ));
buf.push("<!-- Custom styles for this template-->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 21, "index.jade" ));
buf.push("<link href=\"css/dashboard.css\" rel=\"stylesheet\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 22, "index.jade" ));
buf.push("<link href=\"css/dashboard_extend.css\" rel=\"stylesheet\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 23, "index.jade" ));
buf.push("<body>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 24, "index.jade" ));
buf.push("<nav class=\"navbar navbar-inverse navbar-fixed-top\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 25, "index.jade" ));
buf.push("<div class=\"container-fluid\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 26, "index.jade" ));
buf.push("<div class=\"navbar-header\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 27, "index.jade" ));
buf.push("<button type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\" class=\"navbar-toggle collapsed\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 28, "index.jade" ));
buf.push("<span class=\"sr-only\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 28, jade_debug[0].filename ));
buf.push("Toggle navigation");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 29, "index.jade" ));
buf.push("<span class=\"icon-bar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 30, "index.jade" ));
buf.push("<span class=\"icon-bar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 31, "index.jade" ));
buf.push("<span class=\"icon-bar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 32, "index.jade" ));
buf.push("<a href=\"/index\" class=\"navbar-brand\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 32, jade_debug[0].filename ));
buf.push("ScoreBoard");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 33, "index.jade" ));
buf.push("<div id=\"navbar\" class=\"navbar-collapse collapse\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 34, "index.jade" ));
buf.push("<ul class=\"nav navbar-nav navbar-right\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 35, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 36, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 36, jade_debug[0].filename ));
buf.push("Dashboard");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 37, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 38, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 38, jade_debug[0].filename ));
buf.push("Settings");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 39, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 40, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 40, jade_debug[0].filename ));
buf.push("Profile");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 41, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 42, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 42, jade_debug[0].filename ));
buf.push("Help");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</nav>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 43, "index.jade" ));
buf.push("<div class=\"container-fluid\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 44, "index.jade" ));
buf.push("<div class=\"row\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 45, "index.jade" ));
buf.push("<div class=\"col-sm-3 col-md-2 sidebar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 46, "index.jade" ));
buf.push("<ul class=\"nav nav-sidebar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 47, "index.jade" ));
buf.push("<li class=\"active\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 48, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 49, "index.jade" ));
buf.push("Main Controls ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 50, "index.jade" ));
buf.push("<span class=\"sr-only\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 50, jade_debug[0].filename ));
buf.push("(current)");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 51, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 52, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 52, jade_debug[0].filename ));
buf.push("Team Selection");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 53, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 54, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 54, jade_debug[0].filename ));
buf.push("Recovery");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 55, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 56, "index.jade" ));
buf.push("<a href=\"/scoretracker\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 56, jade_debug[0].filename ));
buf.push("Score tracker");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 57, "index.jade" ));
buf.push("<ul class=\"nav nav-sidebar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 58, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 59, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 59, jade_debug[0].filename ));
buf.push("Nav item");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 60, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 61, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 61, jade_debug[0].filename ));
buf.push("Nav item again");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 62, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 63, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 63, jade_debug[0].filename ));
buf.push("One more nav");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 64, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 65, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 65, jade_debug[0].filename ));
buf.push("Another nav item");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 66, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 67, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 67, jade_debug[0].filename ));
buf.push("More navigation");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 68, "index.jade" ));
buf.push("<div ng-app=\"JTApp\" ng-controller=\"buttonsCtrl\" class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 69, "index.jade" ));
buf.push("<h1 class=\"page-header\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 69, jade_debug[0].filename ));
buf.push("Dashboard");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 70, "index.jade" ));
buf.push("<div class=\"row placeholders\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 71, "index.jade" ));
buf.push("<div class=\"col-sm-3 col-md-2 sidebar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 72, "index.jade" ));
buf.push("<ul class=\"nav nav-sidebar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 73, "index.jade" ));
buf.push("<li class=\"active\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 74, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 75, "index.jade" ));
buf.push("Main Controls ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 76, "index.jade" ));
buf.push("<span class=\"sr-only\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 76, jade_debug[0].filename ));
buf.push("(current)");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 77, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 78, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 78, jade_debug[0].filename ));
buf.push("Team Selection");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 79, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 80, "index.jade" ));
buf.push("<a href=\"#\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 80, jade_debug[0].filename ));
buf.push("Recovery");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 81, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 82, "index.jade" ));
buf.push("<a href=\"/scoretracker\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 82, jade_debug[0].filename ));
buf.push("Score tracker");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 83, "index.jade" ));
buf.push("<ul class=\"nav nav-sidebar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 84, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 85, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 85, jade_debug[0].filename ));
buf.push("Nav item");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 86, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 87, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 87, jade_debug[0].filename ));
buf.push("Nav item again");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 88, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 89, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 89, jade_debug[0].filename ));
buf.push("One more nav");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 90, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 91, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 91, jade_debug[0].filename ));
buf.push("Another nav item");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 92, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 93, "index.jade" ));
buf.push("<a href=\"\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 93, jade_debug[0].filename ));
buf.push("More navigation");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 94, "index.jade" ));
buf.push("<div class=\"col-xs-6 col-sm-3 placeholder\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 95, "index.jade" ));
buf.push("<h2 class=\"sub-header\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 95, jade_debug[0].filename ));
buf.push("Primary Controls");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 96, "index.jade" ));
buf.push("<button type=\"button\" ng-click=\"click('start')\" class=\"btn btn-lg btn-success\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 96, jade_debug[0].filename ));
buf.push("Start Jam");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 97, "index.jade" ));
buf.push("<button type=\"button\" ng-click=\"click('stop')\" class=\"btn btn-lg btn-danger\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 97, jade_debug[0].filename ));
buf.push("Stop Jam");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 98, "index.jade" ));
buf.push("<button type=\"button\" ng-click=\"click('callTTO')\" class=\"btn btn-lg btn-info\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 98, jade_debug[0].filename ));
buf.push("TTO");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 99, "index.jade" ));
buf.push("<button type=\"button\" ng-click=\"click('callOTO')\" class=\"btn btn-lg btn-warning\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 99, jade_debug[0].filename ));
buf.push("OTO");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 100, "index.jade" ));
buf.push("<button type=\"button\" class=\"btn btn-lg btn-default\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 100, jade_debug[0].filename ));
buf.push("Default");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 101, "index.jade" ));
buf.push("<button type=\"button\" class=\"btn btn-lg btn-primary\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 101, jade_debug[0].filename ));
buf.push("Primary");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 102, "index.jade" ));
buf.push("<div class=\"col-xs-6 col-sm-3 placeholder\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 103, "index.jade" ));
buf.push("<h2 class=\"sub-header\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 103, jade_debug[0].filename ));
buf.push("Game Clocks");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 104, "index.jade" ));
buf.push("<div ng-controller=\"timersCtrl\" class=\"table-responsive\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 105, "index.jade" ));
buf.push("<table class=\"table table-striped\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 106, "index.jade" ));
buf.push("<tbody>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 107, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 108, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 108, jade_debug[0].filename ));
buf.push("Period Clock");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 109, "index.jade" ));
buf.push("<td class=\"clockOutput\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 110, "index.jade" ));
buf.push("{{pClock | date:'mm:ss'}} ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 111, "index.jade" ));
buf.push("<div role=\"group\" aria-label=\"...\" class=\"btn-group btn-group-justified\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 112, "index.jade" ));
buf.push("<div role=\"group\" class=\"btn-group\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 113, "index.jade" ));
buf.push("<button type=\"button\" onclick=\"upDownClick('pClock', 60)\" class=\"btn btn-default\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 114, "index.jade" ));
buf.push("<span aria-hidden=\"true\" class=\"glyphicon glyphicon-menu-up upDown\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 115, "index.jade" ));
buf.push("<div role=\"group\" class=\"btn-group\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 116, "index.jade" ));
buf.push("<button type=\"button\" onclick=\"upDownClick('pClock', -60)\" class=\"btn btn-default\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 117, "index.jade" ));
buf.push("<span aria-hidden=\"true\" class=\"glyphicon glyphicon-menu-down upDown\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 118, "index.jade" ));
buf.push("<div role=\"group\" class=\"btn-group\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 119, "index.jade" ));
buf.push("<button type=\"button\" onclick=\"upDownClick('pClock', 1)\" style=\"border-left-width: thick; border-left-color: hotpink;\" class=\"btn btn-default\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 120, "index.jade" ));
buf.push("<span aria-hidden=\"true\" class=\"glyphicon glyphicon-menu-up upDown\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 121, "index.jade" ));
buf.push("<div role=\"group\" class=\"btn-group\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 122, "index.jade" ));
buf.push("<button type=\"button\" onclick=\"upDownClick('pClock', -1)\" class=\"btn btn-default\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 123, "index.jade" ));
buf.push("<span aria-hidden=\"true\" class=\"glyphicon glyphicon-menu-down upDown\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 124, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 125, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 125, jade_debug[0].filename ));
buf.push("Jam Clock");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 126, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 126, jade_debug[0].filename ));
buf.push(" {{jClock | date:'mm:ss'}} ");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 127, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 128, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 128, jade_debug[0].filename ));
buf.push("Line Up Clock");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 129, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 129, jade_debug[0].filename ));
buf.push(" {{lClock | date:'mm:ss'}} ");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 130, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 131, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 131, jade_debug[0].filename ));
buf.push("Team Timeout clock");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 132, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 132, jade_debug[0].filename ));
buf.push(" {{TTOClock | date:'mm:ss'}} ");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 133, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 134, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 134, jade_debug[0].filename ));
buf.push("Official Timeout Clock");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 135, "index.jade" ));
buf.push("<td>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 135, jade_debug[0].filename ));
buf.push(" {{OTOClock | date:'mm:ss'}} ");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tbody>");
jade_debug.shift();
jade_debug.shift();
buf.push("</table>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 136, "index.jade" ));
buf.push("<div ng-controller=\"scores\" class=\"col-xs-6 col-sm-3 placeholder\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 137, "index.jade" ));
buf.push("<h2 class=\"sub-header\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 137, jade_debug[0].filename ));
buf.push("Score - Jam Num:  {{jamNumber}}  ");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 138, "index.jade" ));
buf.push("<div class=\"table-responsive\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 139, "index.jade" ));
buf.push("<table class=\"table table-striped\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 140, "index.jade" ));
buf.push("<tbody>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 141, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 142, "index.jade" ));
buf.push("<td id=\"home\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 142, jade_debug[0].filename ));
buf.push("Team1");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 143, "index.jade" ));
buf.push("<td id=\"away\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 143, jade_debug[0].filename ));
buf.push("Team2");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 144, "index.jade" ));
buf.push("<tr>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 145, "index.jade" ));
buf.push("<td id=\"homeScore\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 145, jade_debug[0].filename ));
buf.push(" {{homeScore}} ");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 146, "index.jade" ));
buf.push("<td id=\"awayScore\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 146, jade_debug[0].filename ));
buf.push(" {{awayScore}} ");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tbody>");
jade_debug.shift();
jade_debug.shift();
buf.push("</table>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 147, "index.jade" ));
buf.push("<div class=\"col-xs-6 col-sm-3 placeholder\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 150, "index.jade" ));
buf.push("<!--");
jade_debug.unshift(new jade.DebugItem( 148, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 150, jade_debug[0].filename ));
buf.push("Bootstrap core JavaScript");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 150, jade_debug[0].filename ));
buf.push("==================================================");
jade_debug.shift();
jade_debug.shift();
buf.push("-->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 152, "index.jade" ));
buf.push("<!-- Placed at the end of the document so the pages load faster-->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 152, "index.jade" ));
buf.push("<script src=\"js/angular_jamtimer.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 153, "index.jade" ));
buf.push("<script src=\"js/bootstrap.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\r\nhtml(lang='en')\r\n  head\r\n    meta(charset='utf-8')\r\n    meta(http-equiv='X-UA-Compatible', content='IE=edge')\r\n    meta(name='viewport', content='width=device-width, initial-scale=1')\r\n    // The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags\r\n    meta(name='description', content='')\r\n    meta(name='author', content='')\r\n    link(rel='icon', href='icon.ico')\r\n    script(src='js/angular.js')\r\n    script(src='js/jquery-2.1.3.js')\r\n    script(src='/js/socket.io.js')\r\n    script(src='js/key_controls.js')\r\n    script(src='js/score_interactions.js')\r\n    script(src='js/adjustClocks.js')\r\n    title Scoreboard Application\r\n    // Bootstrap core CSS\r\n    link(href='css/bootstrap.min.css', rel='stylesheet')\r\n    // Custom styles for this template\r\n    link(href='css/dashboard.css', rel='stylesheet')\r\n    link(href='css/dashboard_extend.css', rel='stylesheet')\r\n  body\r\n    nav.navbar.navbar-inverse.navbar-fixed-top\r\n      .container-fluid\r\n        .navbar-header\r\n          button.navbar-toggle.collapsed(type='button', data-toggle='collapse', data-target='#navbar', aria-expanded='false', aria-controls='navbar')\r\n            span.sr-only Toggle navigation\r\n            span.icon-bar\r\n            span.icon-bar\r\n            span.icon-bar\r\n          a.navbar-brand(href='/index') ScoreBoard\r\n        #navbar.navbar-collapse.collapse\r\n          ul.nav.navbar-nav.navbar-right\r\n            li\r\n              a(href='#') Dashboard\r\n            li\r\n              a(href='#') Settings\r\n            li\r\n              a(href='#') Profile\r\n            li\r\n              a(href='#') Help\r\n    .container-fluid\r\n      .row\r\n        .col-sm-3.col-md-2.sidebar\r\n          ul.nav.nav-sidebar\r\n            li.active\r\n              a(href='#')\r\n                | Main Controls \r\n                span.sr-only (current)\r\n            li\r\n              a(href='#') Team Selection\r\n            li\r\n              a(href='#') Recovery\r\n            li\r\n              a(href='/scoretracker') Score tracker\r\n          ul.nav.nav-sidebar\r\n            li\r\n              a(href='') Nav item\r\n            li\r\n              a(href='') Nav item again\r\n            li\r\n              a(href='') One more nav\r\n            li\r\n              a(href='') Another nav item\r\n            li\r\n              a(href='') More navigation\r\n        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main(ng-app='JTApp', ng-controller='buttonsCtrl')\r\n          h1.page-header Dashboard\r\n          .row.placeholders\r\n            .col-sm-3.col-md-2.sidebar\r\n              ul.nav.nav-sidebar\r\n                li.active\r\n                  a(href='#')\r\n                    | Main Controls \r\n                    span.sr-only (current)\r\n                li\r\n                  a(href='#') Team Selection\r\n                li\r\n                  a(href='#') Recovery\r\n                li\r\n                  a(href='/scoretracker') Score tracker\r\n              ul.nav.nav-sidebar\r\n                li\r\n                  a(href='') Nav item\r\n                li\r\n                  a(href='') Nav item again\r\n                li\r\n                  a(href='') One more nav\r\n                li\r\n                  a(href='') Another nav item\r\n                li\r\n                  a(href='') More navigation\r\n            .col-xs-6.col-sm-3.placeholder\r\n              h2.sub-header Primary Controls\r\n              button.btn.btn-lg.btn-success(type='button', ng-click=\"click('start')\") Start Jam\r\n              button.btn.btn-lg.btn-danger(type='button', ng-click=\"click('stop')\") Stop Jam\r\n              button.btn.btn-lg.btn-info(type='button', ng-click=\"click('callTTO')\") TTO\r\n              button.btn.btn-lg.btn-warning(type='button', ng-click=\"click('callOTO')\") OTO\r\n              button.btn.btn-lg.btn-default(type='button') Default\r\n              button.btn.btn-lg.btn-primary(type='button') Primary\r\n            .col-xs-6.col-sm-3.placeholder\r\n              h2.sub-header Game Clocks\r\n              .table-responsive(ng-controller='timersCtrl')\r\n                table.table.table-striped\r\n                  tbody\r\n                    tr\r\n                      td Period Clock\r\n                      td.clockOutput\r\n                        | {{pClock | date:'mm:ss'}} \r\n                        .btn-group.btn-group-justified(role='group', aria-label='...')\r\n                          .btn-group(role='group')\r\n                            button.btn.btn-default(type='button', onclick=\"upDownClick('pClock', 60)\")\r\n                              span.glyphicon.glyphicon-menu-up.upDown(aria-hidden='true')\r\n                          .btn-group(role='group')\r\n                            button.btn.btn-default(type='button', onclick=\"upDownClick('pClock', -60)\")\r\n                              span.glyphicon.glyphicon-menu-down.upDown(aria-hidden='true')\r\n                          .btn-group(role='group')\r\n                            button.btn.btn-default(type='button', onclick=\"upDownClick('pClock', 1)\", style='border-left-width: thick; border-left-color: hotpink;')\r\n                              span.glyphicon.glyphicon-menu-up.upDown(aria-hidden='true')\r\n                          .btn-group(role='group')\r\n                            button.btn.btn-default(type='button', onclick=\"upDownClick('pClock', -1)\")\r\n                              span.glyphicon.glyphicon-menu-down.upDown(aria-hidden='true')\r\n                    tr\r\n                      td Jam Clock\r\n                      td  {{jClock | date:'mm:ss'}} \r\n                    tr\r\n                      td Line Up Clock\r\n                      td  {{lClock | date:'mm:ss'}} \r\n                    tr\r\n                      td Team Timeout clock\r\n                      td  {{TTOClock | date:'mm:ss'}} \r\n                    tr\r\n                      td Official Timeout Clock\r\n                      td  {{OTOClock | date:'mm:ss'}} \r\n            .col-xs-6.col-sm-3.placeholder(ng-controller='scores')\r\n              h2.sub-header Score - Jam Num:  {{jamNumber}}  \r\n              .table-responsive\r\n                table.table.table-striped\r\n                  tbody\r\n                    tr\r\n                      td#home Team1\r\n                      td#away Team2\r\n                    tr\r\n                      td#homeScore  {{homeScore}} \r\n                      td#awayScore  {{awayScore}} \r\n            .col-xs-6.col-sm-3.placeholder\r\n      //\r\n        Bootstrap core JavaScript\r\n        ==================================================\r\n      // Placed at the end of the document so the pages load faster\r\n      script(src='js/angular_jamtimer.js')\r\n      script(src='js/bootstrap.min.js')\r\n");
}
}